backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)


publish_mode: editorial_workflow
media_folder: "img"
public_folder: "img"

local_backend: true

collections:
  - label: "Products"
    name: "products"
    folder: "src/products"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "producttitle", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
  - label: "Blog"
    name: "blog"
    folder: "src/blog"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Text", name: "body", widget: "markdown" }
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        file: "src/index.md"
        fields:
          - { label: "Background Image", name: "image", widget: "image"}